version: '3'

services:

    postgres:
        image: postgres:15-alpine
        container_name: postgres_container
        hostname: postgres
        restart: on-failure
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./postgres_volume/var/run/docker.sock:/var/run/docker.sock
        networks:
            - backend

    localstack:
        image: localstack/localstack:latest
        container_name: localstack_container
        hostname: localstack
        restart: on-failure
        env_file:
            - .env
        environment:
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
            - EDGE_PORT=${EDGE_PORT}
            - SERVICES=${SERVICES}
            - LOCALSTACK_HOST=localstack
        ports:
            - "4566:4566"
        volumes:
            - ./localstack_volume:/var/lib/localstack
            - ./localstack_volume/var/run/docker.sock:/var/run/docker.sock
        networks:
            - backend

    redis:
        image: redis:7.2-alpine
        container_name: redis_container
        hostname: redis
        restart: on-failure
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - backend

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_container
        restart: on-failure
        env_file:
            - .env
        depends_on:
            - postgres
            - redis
            - localstack
        ports:
            - "8000:8000"
        command: sh -c "poetry run alembic upgrade head && poetry run python app/main.py"
        networks:
            - backend

volumes:
    postgres_data:
    redis_data:


networks:
    backend:
        driver: bridge
